"use strict";
const schema={
 core_intent_preserved:["YES","NO","UNCLEAR"],single_requirement_change:["YES","NO","UNCLEAR"],changed_requirement_correct:["YES","NO","UNCLEAR"],
 requirement_family:["COLOR","BRAND","NUMERIC_SPECIFICATION","EXPLICIT_ATTRIBUTE","NEGATION_EXCLUSION","QUANTITY_PACK_SIZE","OTHER","UNCLEAR"],
 operation:["REPLACE","ADD","REMOVE","NEGATE","UNCLEAR"],query_naturalness:["YES","NO","UNCLEAR"],semantic_plausibility:["YES","NO","UNCLEAR"],confidence:["HIGH","MEDIUM","LOW"],
 candidate_direction:["A_SHOULD_GAIN","B_SHOULD_GAIN","NO_REQUIRED_DIRECTION","INSUFFICIENT_EVIDENCE"],direction_confidence:["HIGH","MEDIUM","LOW"]};
const queryFields=["core_intent_preserved","single_requirement_change","changed_requirement_correct","requirement_family","operation","query_naturalness","semantic_plausibility","confidence","old_value_normalized","new_value_normalized"];
const directionFields=["candidate_direction","direction_confidence"];
let data=null,index=0,dirty=false;
const $=id=>document.getElementById(id), esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
$("mode").onchange=()=>$("calibration-options").hidden=$("mode").value!=="CALIBRATION";
function actualMode(){if($("mode").value!=="CALIBRATION")return $("mode").value;return `CALIBRATION_${$("cal-annotator").value}_${$("cal-task").value}`}
function answerControl(field,value){if(schema[field])return `<select data-answer="${field}"><option value=""></option>${schema[field].map(v=>`<option ${value===v?"selected":""}>${v}</option>`).join("")}</select>`;return `<input type="text" data-answer="${field}" value="${esc(value)}">`}
function sourceBlock(row){return `<section class="source"><h2>${esc(row.example_id||row.direction_item_id)}</h2><div class="queries"><div><h3>Query A</h3><div class="value">${esc(row.query_a)}</div></div><div><h3>Query B</h3><div class="value">${esc(row.query_b)}</div></div></div>${row.proposed_requirement_family!==undefined?`<div class="grid"><p><b>Proposed product type</b><br>${esc(row.proposed_invariant_product_type)}</p><p><b>Proposed requirement family</b><br>${esc(row.proposed_requirement_family)}</p><p><b>Proposed operation</b><br>${esc(row.proposed_operation)}</p><p><b>Proposed values</b><br>${esc(row.proposed_old_value)} → ${esc(row.proposed_new_value)}</p></div>`:""}</section>`}
function candidate(row,side){const title=`Candidate ${side.toUpperCase()}`, p=`candidate_${side}_`;return `<section class="candidate"><h3>${title}</h3><div class="metadata"><dl><dt>Product ID</dt><dd>${esc(row[p+"id"])}</dd><dt>Visible evidence</dt><dd>${esc(row[p+"visible_evidence"])}</dd><dt>Title</dt><dd>${esc(row[p+"product_title"])}</dd><dt>Brand</dt><dd>${esc(row[p+"product_brand"])}</dd><dt>Color</dt><dd>${esc(row[p+"product_color"])}</dd><dt>Bullet points</dt><dd>${esc(row[p+"product_bullet_point"])}</dd><dt>Description</dt><dd>${esc(row[p+"product_description"])}</dd></dl></div></section>`}
function render(){const row=data.rows[index], fields=data.answer_fields;let html=sourceBlock(row);if(fields.includes("candidate_direction"))html+=`<div class="candidates">${candidate(row,"a")}${candidate(row,"b")}</div>`;html+=`<section class="answers"><h2>Human answers</h2><div class="grid">${fields.map(f=>`<div class="field answer-field"><label>${esc(f)}</label>${answerControl(f,row[f]||"")}</div>`).join("")}</div></section>`;$("card").innerHTML=html;document.querySelectorAll("[data-answer]").forEach(el=>el.onchange=()=>{row[el.dataset.answer]=el.value;dirty=true;updateStatus()});$("progress").textContent=`${index+1} / ${data.rows.length}`;$("jump").value=String(index);updateStatus()}
function state(row){const values=data.answer_fields.map(f=>row[f]||"");return values.every(Boolean)?"COMPLETE":values.some(Boolean)?"PARTIAL":"UNANNOTATED"}
function updateStatus(){const s=state(data.rows[index]);$("status").textContent=s;$("status").className=`status ${s.toLowerCase()}`;$("completed").textContent=`Completed: ${data.rows.filter(r=>state(r)==="COMPLETE").length}`}
async function load(){const mode=actualMode();if(!mode)return;const response=await fetch(`/api/data?mode=${encodeURIComponent(mode)}`);data=await response.json();if(data.error)return alert(data.error);index=0;dirty=false;$("chooser").hidden=true;$("workspace").hidden=false;$("phase").textContent=data.phase==="CALIBRATION_ONLY"?"CALIBRATION ONLY — keep separate from final annotations":"FINAL INDEPENDENT ANNOTATION";$("jump").innerHTML=data.rows.map((r,i)=>`<option value="${i}">${i+1}: ${esc(r[data.key])}</option>`).join("");render()}
async function save(){const rows=data.rows.map(r=>{const out={[data.key]:r[data.key]};data.answer_fields.forEach(f=>out[f]=r[f]||"");return out});const response=await fetch("/api/save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:data.mode,rows})});const result=await response.json();if(result.error)return alert(result.error);dirty=false;alert(`Saved ${result.row_count} rows. Complete: ${result.completed}.`)}
$("load").onclick=load;$("save").onclick=save;$("previous").onclick=()=>{if(index>0){index--;render()}};$("next").onclick=()=>{if(index<data.rows.length-1){index++;render()}};$("jump").onchange=e=>{index=Number(e.target.value);render()};
document.addEventListener("keydown",e=>{if(e.altKey&&e.key==="ArrowLeft")$("previous").click();if(e.altKey&&e.key==="ArrowRight")$("next").click();if(e.ctrlKey&&e.key.toLowerCase()==="s"){e.preventDefault();if(data)save()}});window.addEventListener("beforeunload",e=>{if(dirty){e.preventDefault();e.returnValue=""}});
